name: VibeTest CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Test on ${{ matrix.os }} with ${{ matrix.browser }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        browser: [chrome, firefox]
        java-version: [17]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Java ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    # WebDriverManager will handle driver setup automatically
    - name: Display environment info
      run: |
        echo "Testing on ${{ matrix.os }} with ${{ matrix.browser }}"
        echo "Java version: $(java -version 2>&1 | head -n 1)"
        echo "Maven version: $(mvn -version | head -n 1)"
        echo "Available browsers:"
        which google-chrome || echo "Chrome not found"
        which firefox || echo "Firefox not found"
        which msedge || echo "Edge not found"
        
    - name: Setup CI test configuration
      run: |
        echo "Setting up CI test configuration..."
        cp testng-ci.xml testng.xml
        echo "TestNG configuration updated for CI"
        echo "TestNG configuration content:"
        cat testng.xml
      
    - name: Run Tests
      env:
        BROWSER: ${{ matrix.browser }}
        CHROME_HEADLESS: true
        FIREFOX_HEADLESS: true
        EDGE_HEADLESS: true
      run: |
        echo "Running tests on ${{ matrix.os }} with ${{ matrix.browser }}"
        echo "Current directory: $(pwd)"
        echo "Listing target directory:"
        ls -la target/ || echo "Target directory doesn't exist yet"
        echo "Running Maven tests..."
        mvn clean test -Dbrowser=${{ matrix.browser }} -Dheadless=true -Dwebdriver.timeouts.implicitlywait=10 -X || echo "Tests failed but continuing..."
        echo "Test execution completed. Checking results..."
        echo "Target directory contents:"
        ls -la target/ || echo "Target directory not found"
        echo "Surefire reports:"
        ls -la target/surefire-reports/ || echo "No surefire reports found"
        echo "Extent reports:"
        ls -la target/extent-reports/ || echo "No extent reports found"
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.os }}-${{ matrix.browser }}
        path: |
          target/surefire-reports/
          target/extent-reports/
          target/screenshots/
        retention-days: 30
        
    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: logs-${{ matrix.os }}-${{ matrix.browser }}
        path: |
          target/logs/
          *.log
        retention-days: 30

  code-quality:
    name: Code Quality Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Compile code
      run: mvn clean compile
      
    - name: Organize imports
      run: mvn spotless:apply
      
    - name: Check code style
      run: mvn checkstyle:check
      
    - name: Verify project structure
      run: |
        echo "Project structure verification:"
        echo "Source files:"
        find src/main/java -name "*.java" | wc -l
        echo "Test files:"
        find src/test/java -name "*.java" | wc -l
        echo "Resource files:"
        find src/main/resources -name "*" 2>/dev/null | wc -l || echo "No main resources"
        find src/test/resources -name "*" 2>/dev/null | wc -l || echo "No test resources"

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Run OWASP dependency check
      run: mvn org.owasp:dependency-check-maven:check
      
    - name: Upload security report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-report
        path: target/dependency-check-report.html
        retention-days: 30

  report:
    name: Generate and Deploy Reports
    runs-on: ubuntu-latest
    needs: [test, code-quality]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Download test artifacts
      uses: actions/download-artifact@v4
      with:
        path: test-results/
        
    - name: Generate consolidated report
      run: |
        mkdir -p reports
        echo "# VibeTest Test Results" > reports/README.md
        echo "Generated on: $(date)" >> reports/README.md
        echo "" >> reports/README.md
        echo "## Test Summary" >> reports/README.md
        find test-results -name "*.html" -exec echo "- [{}]({})" \; >> reports/README.md
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: success()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./reports
        publish_branch: gh-pages 