name: Pull Request Validation

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  validate:
    name: Validate PR
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Validate POM
      run: mvn validate
      
    - name: Compile code
      run: mvn clean compile
      
    - name: Run unit tests
      run: mvn test -Dtest=!*IntegrationTest
      
    - name: Check code style
      run: mvn checkstyle:check
      
    - name: Organize imports
      run: mvn spotless:apply
      
    - name: Comment PR
      uses: actions/github-script@v7
      if: always()
      with:
        script: |
          const { data: comments } = await github.rest.issues.listComments({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          
          const botComment = comments.find(comment => 
            comment.user.type === 'Bot' && 
            comment.body.includes('## PR Validation Results')
          );
          
          const status = '${{ job.status }}';
          const emoji = status === 'success' ? '✅' : '❌';
          
          const commentBody = `## PR Validation Results ${emoji}
          
          **Status**: ${status}
          **Triggered by**: @${{ github.actor }}
          **Branch**: ${{ github.head_ref }}
          
          ### Checks Completed:
          - ✅ POM Validation
          - ✅ Code Compilation
          - ✅ Unit Tests
          - ✅ Code Style Check
          - ✅ Import Organization
          
          ${status === 'success' ? '🎉 All checks passed! Ready for review.' : '⚠️ Some checks failed. Please review the logs.'}
          
          ---
          *This comment was automatically generated by GitHub Actions*`;
          
          if (botComment) {
            await github.rest.issues.updateComment({
              comment_id: botComment.id,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });
          } else {
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });
          } 